name: async_util
version: 0.0.1
description: Utility classes and functions to make async operations with dart easier
author: Scott Pierce
homepage: https://github.com/ScottPierce/async_util

environment:
  sdk: '>=1.0.0 <2.0.0'


dev_dependencies:
  test: "^0.12.13+4"